title "Cualquier" tecnología

class 5Primeros{
Escopeta de feria
---
* Lo acaban de pulir
* Se aplica donde no debe
* Facciones que pelean por la autoría
}


class 5Siguientes{
Reducción del ruido
---
* Se estudia
* Se contraestudia
* Tesis / Antítesis / Síntesis
}

class 5Posteriores{
* Se asienta
* Se conoce lo valido
* Se estandariza
}

5Primeros-r->5Siguientes
5Siguientes-r->5Posteriores
